// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ClassOutline
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidClassOutlinePackageString = "e7427165-9eb1-43ef-a971-b50ad3b6f4bb";
        public static Guid guidClassOutlinePackage = new Guid(guidClassOutlinePackageString);

        public const string guidClassOutlinePackageCmdSetString = "0839aa3b-8e7b-4d88-852b-d93e72cccf4d";
        public static Guid guidClassOutlinePackageCmdSet = new Guid(guidClassOutlinePackageCmdSetString);

        public const string guidImagesString = "dec20cb1-44d3-4c9a-ac55-e145114b61b9";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MainWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}